// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/octopus/pkg/models/shared"
	"net/http"
)

type GetCampaignsCampaignIDRequest struct {
	CampaignID string `pathParam:"style=simple,explode=false,name=campaignId"`
}

func (o *GetCampaignsCampaignIDRequest) GetCampaignID() string {
	if o == nil {
		return ""
	}
	return o.CampaignID
}

type GetCampaignsCampaignIDResponse struct {
	// Campaign found
	Campaign    *shared.Campaign
	ContentType string
	// Error
	ErrorResponse *shared.ErrorResponse
	StatusCode    int
	RawResponse   *http.Response
}

func (o *GetCampaignsCampaignIDResponse) GetCampaign() *shared.Campaign {
	if o == nil {
		return nil
	}
	return o.Campaign
}

func (o *GetCampaignsCampaignIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCampaignsCampaignIDResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *GetCampaignsCampaignIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCampaignsCampaignIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
