// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/octopus/pkg/models/shared"
	"net/http"
)

type PutCampaignsCampaignIDRequest struct {
	CampaignRequest shared.CampaignRequest `request:"mediaType=application/json"`
	CampaignID      string                 `pathParam:"style=simple,explode=false,name=campaignId"`
}

func (o *PutCampaignsCampaignIDRequest) GetCampaignRequest() shared.CampaignRequest {
	if o == nil {
		return shared.CampaignRequest{}
	}
	return o.CampaignRequest
}

func (o *PutCampaignsCampaignIDRequest) GetCampaignID() string {
	if o == nil {
		return ""
	}
	return o.CampaignID
}

type PutCampaignsCampaignIDResponse struct {
	// Campaign updated successfully
	Campaign    *shared.Campaign
	ContentType string
	// Error
	ErrorResponse *shared.ErrorResponse
	StatusCode    int
	RawResponse   *http.Response
}

func (o *PutCampaignsCampaignIDResponse) GetCampaign() *shared.Campaign {
	if o == nil {
		return nil
	}
	return o.Campaign
}

func (o *PutCampaignsCampaignIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutCampaignsCampaignIDResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *PutCampaignsCampaignIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutCampaignsCampaignIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
