// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Campaign struct {
	// Campaign body
	Body *string `json:"body,omitempty"`
	// Campaign from address
	From *string `json:"from,omitempty"`
	// Campaign ID
	ID *string `json:"id,omitempty"`
	// Campaign name
	Name *string `json:"name,omitempty"`
	// Campaign reply to address
	ReplyTo *string `json:"replyTo,omitempty"`
	// Campaign schedule
	Schedule *string `json:"schedule,omitempty"`
	// Campaign status
	Status *string `json:"status,omitempty"`
	// Campaign subject
	Subject *string `json:"subject,omitempty"`
}

func (o *Campaign) GetBody() *string {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *Campaign) GetFrom() *string {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *Campaign) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Campaign) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Campaign) GetReplyTo() *string {
	if o == nil {
		return nil
	}
	return o.ReplyTo
}

func (o *Campaign) GetSchedule() *string {
	if o == nil {
		return nil
	}
	return o.Schedule
}

func (o *Campaign) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Campaign) GetSubject() *string {
	if o == nil {
		return nil
	}
	return o.Subject
}
