// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CampaignSending struct {
	// Campaign ID
	CampaignID *string `json:"campaignId,omitempty"`
	// Number of emails sent
	SendCount *int64 `json:"sendCount,omitempty"`
}

func (o *CampaignSending) GetCampaignID() *string {
	if o == nil {
		return nil
	}
	return o.CampaignID
}

func (o *CampaignSending) GetSendCount() *int64 {
	if o == nil {
		return nil
	}
	return o.SendCount
}
