// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CampaignRequest struct {
	// Campaign body
	Body *string `json:"body,omitempty"`
	// Campaign from address
	From *string `json:"from,omitempty"`
	// Campaign name
	Name *string `json:"name,omitempty"`
	// Campaign reply to address
	ReplyTo *string `json:"replyTo,omitempty"`
	// Campaign schedule
	Schedule *string `json:"schedule,omitempty"`
	// Campaign subject
	Subject *string `json:"subject,omitempty"`
}

func (o *CampaignRequest) GetBody() *string {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *CampaignRequest) GetFrom() *string {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *CampaignRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CampaignRequest) GetReplyTo() *string {
	if o == nil {
		return nil
	}
	return o.ReplyTo
}

func (o *CampaignRequest) GetSchedule() *string {
	if o == nil {
		return nil
	}
	return o.Schedule
}

func (o *CampaignRequest) GetSubject() *string {
	if o == nil {
		return nil
	}
	return o.Subject
}
