// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CampaignSendingRequest struct {
	// Campaign ID
	CampaignID *string `json:"campaignId,omitempty"`
}

func (o *CampaignSendingRequest) GetCampaignID() *string {
	if o == nil {
		return nil
	}
	return o.CampaignID
}
