// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ErrorResponse struct {
	// Error message
	Error *string `json:"error,omitempty"`
}

func (o *ErrorResponse) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
