// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Subscription struct {
	// Campaign ID
	CampaignID *string `json:"campaignId,omitempty"`
	// Email address
	Email *string `json:"email,omitempty"`
}

func (o *Subscription) GetCampaignID() *string {
	if o == nil {
		return nil
	}
	return o.CampaignID
}

func (o *Subscription) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}
