// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SubscriptionRequest struct {
	// Email address
	Email *string `json:"email,omitempty"`
}

func (o *SubscriptionRequest) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}
